language: java
jdk:
- oraclejdk8
services:
  - docker
env:
  global:
    - secure: "tlin2n6Vc48e5iqyLsh0qMDnoDzopub780d7jglEmZHnfndolVXheHEVE6xAcGFL8Dp/OrKT/JMEhLFKBW9+YF8QBznSEnlVQ9t6va+5LK5zeeVMChmIHFo5mHXZBZ4nCebVbMleZIlzbjR47+bZNMUU2982gYeIJAmLC3hSFRvVRfh0FlK7mgpSIogSpbq37uzWLMgrEfFOHX7qHuMZdMXbFubQ8pR+1Wd39jf+tauC8wOn3jYDnsomn64rbidKaKIiFApIQO0jh5BNpImB9s50G/lw7Gcqcs0/nmV8w44/9mU0oCy0WDK9vvjbzYA+UN34S3SDRqjdWe4hxIht5Gl153QucpJSVtbHLtK4T10fn6ZfEee61kchhtq1VvbdKtq/S4YQx/egChJoprFerzrF8lO859zZxbbuUwVFunzQ8lpfnejLWbAyrgmkmA2B/Sc6sM5bJZdIrc4NYqMyx91mmUfrctm3njz2UMLHK4aNxvoIurb2j48UoJHf/vg16ryh9QHOW7dbzcnEcxqglzoOlAFcS3tBCpmFS6rZAr5KWZs6T7+O//9yCGfNoUK8zNff1OxINXw5YUckz0z/t6mqtlnUV1PrcEROYH65nKgP/OwtHSZ1PDGKCfRhMob4LfF6fz95AfZjegcmIxiT0LMzsvD/dcO4cPbLKEmBONU="
  
  
script:
- gradle releaseZip
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  api_key:
    secure: ybw1Ycp9bk92wPXunEjp2LEexG1BXK6E52UP/7ka3BMQZT1hgb1E14YUaXO04QywmJSNfTfe31T8JvFFzIChpLNDowjfW6t8C1pxkiul1ewj3/ZsWW4e1yi2JVswkz6IFwO8/9txKkrqF6EFjW3rfQguqgA/utOHz3nuHZBRSEmff/V+rBOEz4m2/AbvfIY2/lZpZjNcUFmWV/E1DsreWptmjYUJ40a55UajtasjoB1o4gjSKI5QpI6lucrUQlLScl8py7s87RRTUDzpigplmGlsGoqsOYI8x1pdZBofUx60wWgb6rk3SbbP9+22nxkQfMp2TA6f/2SLLscaMuR694zra4tdWwOlPtFpRQGIr2nrU1VbI/6lUmK5MslVk83++w7ghsYHkRZDDf3Bcmg2iG+pjVlnOUN+t0I8p8QMkPVPdlhXGOVF/X4owCygqpESfXMiXnS0b7xvqiIwtK8NwsL9monP1KYdpfFvmjiGsq4gHc7iJgwmfVYvHbZCISYm6C1UXhRL9bgInYZa5LeTf27HmT/NerQGtGP9RkfhDRFOCsERQlzQ57PE3joZQ+UYjcaJQ6H2NTVjefzBBk0SpwjNwnql95eYDVz+FFdlmupzYwM6XzesvOw0LPgRLF2hwX7/VE6oqg4EFkCkam5rMaMaQihzPH2aHrJbWucGuLk=
  file: 
  - build/distributions/identio-server-v$TRAVIS_TAG.tar.gz
  - build/distributions/identio-server-v$TRAVIS_TAG.zip  
  on:
    repo: identio/identio-server
after_deploy:
  - curl -H "Content-Type: application/json" --data '{"source_type": "Branch", "source_name": "master"}' -X POST DOCKER_HUB_TRIGGER_URL
  