authPolicyConfiguration:
  authLevels:
    - &low
      name: low
      urn: urn:identio:auth-level:low
    - &medium
      name: medium
      urn: urn:identio:auth-level:medium
    - &strong
      name: strong
      urn: urn:identio:auth-level:strong
  defaultAuthLevel:
    authLevel: *medium
    comparison: minimum

samlIdpConfiguration:
  allowUnsecureRequests: true
  allowedTimeOffset: 1
  certificateCheckEnabled: true
  contactPersonEmail: support@identio.net
  contactPersonSurname: Ident.io Support
  organizationDisplayName: Ident.io Identity Provider
  organizationName: Ident.io
  organizationUrl: http://identio.net
  tokenValidityLength: 3

sessionConfiguration:
  duration: 120
  
authMethodConfiguration:

  localAuthMethods:
  - &local
      name: Local
      authLevel: *medium